### ISSUE TITLE
Documentation/Wiki

### ISSUE THREAD

**Issue by difelice** [brunobasto/Peerflix.bundle#1]
Hi, this is a very interesting project. Can you please add more details like requirements, and install procedure.

Thanks.

**Comment by brunobasto** [comment]
Hello! Thanks for appreciating it. It's still under development, but installation should be pretty straightforward.

Just copy the project folder to your Plex plugins folder. In my Max, for example, it is: /Users/brunobasto/Library/Application Support/Plex Media Server/Plug-ins

**Comment by difelice** [comment]
Hi Bruno, I did exactly what the same, I can't play any video/torrent listed on "Shows". It should automatically get the torrent magnet and run peerflix for me right? Any suggestion to debug it. Thanks a lot.

**Comment by brunobasto** [comment]
If you are trying to play on the Brower plex client, I found that it only
works if you disable direct stream and direct play. Same thing for Android
players. Haven't tested in any other players.

**Comment by difelice** [comment]
Not sure what's the issue, it would be nice to debug the whole process.

How can I see the logs for the Log.Debug/Info calls?

Thanks.

**Comment by brunobasto** [comment]
I created an alias to just that :)

alias peerlog="tail -f /Users/brunobasto/Library/Logs/PMS\ Plugin\ Logs/com.plexapp.plugins.peerflix.log"

You can adjust the path for your environment. Let me know what your findings are. I just remembered: Python wasn't able to find nodejs inside /usr/local/bin so I had to create symbolic link inside /usr/bin/

So, in my environment, the node executable can be found both in /usr/local/bin/node and /usr/bin/node

I have look into that deeper to see how can I execute peerflix without needing those additional changes. But, for now, that's how I managed it to work.

**Comment by brunobasto** [comment]
@difelice 

Where you able to see the log output?

**Comment by difelice** [comment]
Yes @brunobasto thanks, I think the function **PlayHLS** doesn't get called for some reason, these are the last log lines:

```
DEBUG (shows:187) - Found hd quality magnet from eztv provider.
DEBUG (runtime:106) - Sending packed state data (109 bytes)
DEBUG (runtime:918) - Response: [200] VideoClipObject, 1649 bytes
```

I believe the next log should be `Checking if server...`

I'm testing on **Apple TV 3**, **Boxee Box via Plexee** and **Plex Home Theater for Mac**.

Thanks again.

**Comment by brunobasto** [comment]
I haven't tested against those players. Gave tested using the Web client for plex? plex.tv/app 

Remember you have to disable direct stream and direct play. 

I have also tested against the Android client (Nexus 5 and 7) and it worked for most torrents.

**Comment by brunobasto** [comment]
If you have any improvements to make, feel free to send me a pull request. That'd be awesome.

**Comment by difelice** [comment]
Yes @brunobasto, I'm already modifying some files, I'm not an expert on plex plugins so I'll need some time. Thanks!

**Comment by brunobasto** [comment]
Great! I'm no expert either. This is my first one.
